# Generated by Django 4.1.7 on 2023-04-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_profesor_delete_profesores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fecha_entrega',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='entregable',
            name='entregado',
        ),
    ]
